### ISSUE TITLE
Dock sensor is not shown in home app

### ISSUE THREAD

**Issue by Kienz** [nicoh88/homebridge-xiaomi-roborock-vacuum#24]
I enabled ```dock:true``` but the dock sensor is not shown in the apple home app.
I have vaccum v1. In the eve app the vaccum sensor statistics also not shown.

```
homebridge-xiaomi-roborock-vacuum@0.3.2
homebridge@0.4.45  
node@9.8.0
```

**Comment by nicoh88** [comment]
Hi @Kienz,

please, show me your `config.json` and the output of `npm list --depth=0 -g | grep -i xiaomi`.

Kind regards,
Nico

**Comment by Kienz** [comment]
config.json
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "AA:BC:DD:EE:F1:20",
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "ZP",
      "service": "light",
      "brightness": true,
      "speakers": false
    }
  ],
  "accessories": [{
      "accessory": "MiRobotVacuum",
      "name": "Saugroboter",
      "ip": "192.168.1.157",
      "token": "61XXXXXXXXXXXX4XXXXXXX",
      "pause": true,
      "dock": true
     }
  ]
}
```

npm list --depth=0 -g | grep -i xiaomi
```+-- homebridge-xiaomi-roborock-vacuum@0.3.2```

Previously I have the homebridge plugin homebridge-xiaomi-mi-robot-vacuum installed. After deleting this node_module I got this error:
```
[2018-10-12 08:22:33] [ZP] uncaught exception                                                                                                                                                                                                                                                    
Error: The requested accessory 'MiRobotVacuum' was not registered by any plugin.                                                                                                                                                                                                                 
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)                                                                                                                                                                                                                   
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)                                                                                                                                                                                                     
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)                                                                                                                                                                                                                   
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)                                                                                                                                                                                                                  
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)                                                                                                                                                                                                          
    at Module._compile (module.js:649:30)                                                                                                                                                                                                                                                        
    at Object.Module._extensions..js (module.js:660:10)                                                                                                                                                                                                                                          
    at Module.load (module.js:561:32)                                                                                                                                                                                                                                                            
    at tryModuleLoad (module.js:501:12)                                                                                                                                                                                                                                                          
    at Function.Module._load (module.js:493:3)    
```

**Comment by nicoh88** [comment]
Please change `"accessory": "MiRobotVacuum",` in `"accessory": "XiaomiRoborockVacuum",`
