### ISSUE TITLE
Can`t install npm

### ISSUE THREAD

**Issue by hagenfenris** [nicoh88/homebridge-xiaomi-roborock-vacuum#26]
Hallo,
ich kann leider Dein Homebridge-Plugin nicht installieren.
In der CLI kommt folgende Meldung:

pi@raspberrypi:~ $ sudo npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /                        root/.npm/_cacache/tmp/git-clone-bbcf07fc
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-bbcf07fc':                         Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-28T07_35_59_619Z-debug.log
pi@raspberrypi:~ $

Hier noch das Logfile:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-xiaomi-roborock-vacuum',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@5.6.0
3 info using node@v9.7.1
4 verbose npm-session 27c70362197b3c0b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-xiaomi-roborock-vacuum 2199ms
8 silly pacote tag manifest for homebridge-xiaomi-roborock-vacuum@latest fetched in 2775ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-xiaomi-roborock-vacuum@0.3.2 checking installable status
14 silly fetchPackageMetaData error for miio@git://github.com/nicoh88/miio.git#master Command failed: /usr/bin/git clone --de$
14 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-bbcf07fc': Pe$
15 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /root/.np$
15 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-bbcf07fc': Permission deni$
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:273:12)
15 verbose stack     at ChildProcess.emit (events.js:127:13)
15 verbose stack     at maybeClose (internal/child_process.js:936:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:353:11)
15 verbose stack     at Socket.emit (events.js:127:13)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:558:12)
16 verbose cwd /home/pi
17 verbose Linux 4.14.71+
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-xiaomi-roborock-vacuum" "--unsafe-perm"
19 verbose node v9.7.1
20 verbose npm  v5.6.0
21 error code 128
22 error Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /root/.npm/_cacache/tmp/$
22 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-bbcf07fc': Permission denied
23 verbose exit [ 1, true ]

**Comment by nicoh88** [comment]
sudo su -
npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm

**Comment by hagenfenris** [comment]
Danke, mein Fehler.
Mit sudo hatte ich es probiert.
