### ISSUE TITLE
ERR getDevice | Is not a vacuum cleaner! With a roborock.vacuum.c1

### ISSUE THREAD

**Issue by vcdx71** [nicoh88/homebridge-xiaomi-roborock-vacuum#34]
Any idea why this wouldn't work with a C1? I know I have the correct Token, but I get ERR getDevice | Is not a vacuum cleaner! logged when re-starting homebridge, device shows no response in the Home app as well.

**Comment by nicoh88** [comment]
Hi @vcdx71 

what is the exact model name?

At the moment only the Mi Robot (Gen 1) and Roborock S50 / S55 (Gen 2) are supported.

Unfortunately, I do not have a Roborock "C" model here to customize the plugin. Xiaomi does not send me the robots, so I can adapt the plugin. 😢 

Sorry.

**Comment by vcdx71** [comment]
Thanks @nicoh88 It's a Roborock C10, it's this model https://www.amazon.com/gp/product/B07FFNNJ8C. Anything I can do to enable you to support this model?

**Comment by nicoh88** [comment]
You can send me a Roborock C10. Unfortunately, I can not help you otherwise.

**Comment by nicoh88** [comment]
Do you have IT and / or programming skills?

**Comment by vcdx71** [comment]
Yes, I've been in IT for over 20 years.

**Comment by nicoh88** [comment]
It could be at line 327 - here need an OR „roborock.vaacum.c1“? 

But I am not sure. Probably not only the only one.

Not possible without a robot. Sorry

https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L327

**Comment by vcdx71** [comment]
Got further,

[Theater Vac] STA getDevice | Connected to: 192.168.20.200
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | Model: roborock.vacuum.c1
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | State: undefined
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | FanSpeed: undefined
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | BatteryLevel: undefined
[1/17/2019, 4:19:03 PM] [Theater Vac] ERR getDevice | miio.device, next try in 2 minutes | TypeError: result.state is not a function
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | Firmwareversion: 1.3.0
[1/17/2019, 4:19:03 PM] [Theater Vac] STA getDevice | Serialnumber: undefined

**Comment by nicoh88** [comment]
I have an idea - more tomorrow.

**Comment by vcdx71** [comment]
Thanks!

**Comment by nicoh88** [comment]
Hi @vcdx71,

please test the newest GitHub#Master.

`npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm`

Good Luck 🍀

**Comment by nicoh88** [comment]
Again, I have updated it again.

**Comment by vcdx71** [comment]
Very close, can see when it's cleaning or docked, but can't control it.

[1/18/2019, 9:05:22 AM] [Theater Vac] INF getSpeed | roborock.vacuum.c1 | Fanspeed is 62%.
[1/18/2019, 9:05:22 AM] [Theater Vac] INF getCleaning | roborock.vacuum.c1 | Cleaning is true.
[1/18/2019, 9:05:22 AM] [Theater Vac] INF getDocked | roborock.vacuum.c1 | Robot Docked is false.
[1/18/2019, 9:05:40 AM] [Theater Vac] ACT setCleaning | roborock.vacuum.c1 | Stop cleaning and go to charge.
(node:42812) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:16:9)
(node:42812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/18/2019, 9:06:14 AM] [Theater Vac] ACT setCleaning | roborock.vacuum.c1 | Start cleaning, not charging.
[1/18/2019, 9:06:14 AM] [Theater Vac] ACT setCleaning - dock | roborock.vacuum.c1 | Docked set to false.
(node:42812) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:16:9)
(node:42812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by vcdx71** [comment]
Ok I take that back, it can start a cleanup, but it can not stop it or change the "fan speed".

**Comment by nicoh88** [comment]
https://github.com/aholstenson/miio/issues/214
