### ISSUE TITLE
Showing the wrong status

### ISSUE THREAD

**Issue by zlldnv** [nicoh88/homebridge-xiaomi-roborock-vacuum#68]
[9/24/2019, 7:18:38 PM] [Xiaomi Mi Robot Vaccum 2 Generation] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%

This is what does the logs says, but the Vacuum Cleaner is on charging

**Comment by jaredbiehler** [comment]
FWIW I have the same issue and the only way I've been able to use Siri to start the vacuum is to first tell Siri to stop the vacuum, then issue a second command to her to start it.

**Comment by WestCoast5550** [comment]
@jaredbiehler this is what I also doing right now.
Actually I made shortcut for that, but anyway it look like workaround

**Comment by afharo** [comment]
Hey! The vacuum cleaner still reports the last speed when it was on. But you should see it’s reporting it’s in OFF status (speed: 100% but OFF). Is that not the case?

**Comment by jaredbiehler** [comment]
Even up to a few days after the vacuum runs the iOS fan icon’s blade is spinning and the tile itself is lit up as though the vacuum is still running. As well, the next time I want to use it I have to tell Siri to turn it off and then, in a separate command, to turn it back on - this is repeatable and happens every time for me. It’s as though the bridge never receives a message that the vacuum made it back to the base. 

I do clean the vacuum every time it runs which usually triggers a voice message when I physically pick it up “error 3, try placing the vacuum...”. After cleaning, I hit then home button and the vacuum finds its way back fine - maybe something in that process interferes with the normal dock status message.

**Comment by afharo** [comment]
This is the logic to get the cleaning status: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L482
It could explain false negatives. But that’s weird that it gives false positives

**Comment by jaredbiehler** [comment]
I'm running the latest. If I get a few minutes this weekend I'll try to see if I can't figure out how to generate debug messages and I'll share the log(s).

**Comment by afharo** [comment]
@jaredbiehler any findings?

**Comment by ludgats** [comment]
I’m having the same issue for a couple months now. Is there any updates? Thanks!

**Comment by afharo** [comment]
@ludgats can you find any pattern in the logs when it fails to report it's off? It would be nice to narrow this issue down to something we can tackle.

**Comment by ludgats** [comment]
[Homebridge] }

Not sure if this helps..

[Homebridge] [12/27/2019, 20:30:57] [Vacuum] ACT setCleaning | roborock.vacuum.s6 | Stop cleaning and go to charge.
[Homebridge] [12/27/2019, 20:31:09] [Vacuum] ERR setCleaning | roborock.vacuum.s6 | Failed to set cleaning to false Error: Call to device timed out
[Homebridge] at retry (/home/hoobs/.hoobs/node_modules/@hoobs/miio/lib/network.js:493:18)
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/miio/lib/network.js:506:8 {
[Homebridge] code: 'timeout'
[Homebridge] }

**Comment by afharo** [comment]
Ha! So the problem is a network timeout?
Maybe the robot was at a place where the WiFi signal is weak?
What was the behaviour? Did it fail to stop? Or did it successfully stop and go to the dock but homebridge won’t register the change?

**Comment by ludgats** [comment]
If I manual push stop in the home app everything stops as intended. If it finishes the cleaning cycle it going back to the duck but the fan speed still shows spinning. If I ask Siri to stop cleaning it also goes to the dock but still shows as cleaning which makes it an issue the next time I try to run the vacuum. 

This happens every time. The wifi is very strong so I don’t think it’s that. 

Is there anything else I can provide?

**Comment by serbasan** [comment]
Same problem. I have a Mesh network and I imagine it changes antenna during cleaning. Could some reconnection be added to the network?

**Comment by afharo** [comment]
I've been suffering from the same issue myself. Also, it fails to start cleaning from time to time. I finally got some time to spot the behaviour in the logs:

1. First (failed) try:
```
[1/17/2020, 9:01:25 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:01:25 AM] [Roberta] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[1/17/2020, 9:01:25 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:01:25 AM] [Roberta] ACT setCleaning | roborock.vacuum.s5 | Start cleaning, not charging.
2020-01-17T09:01:25.285Z miio:packet -> <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
 ff ff ff ff>
2020-01-17T09:01:25.302Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5e 21 77 e5 ff ff ff ff ff ff ff ff ff ff ff ff
 ff ff ff ff>
2020-01-17T09:01:25.302Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5e 21 77 e5 ff ff ff ff ff ff ff ff ff ff ff ff
 ff ff ff ff>
2020-01-17T09:01:25.303Z thing:miio:96818260 <- Handshake reply: <Buffer ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
```

2. Second failed try:

3. Third failed try:
```
Fri, 17 Jan 2020 09:32:59 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "Lock Target State" to value 1
Fri, 17 Jan 2020 09:32:59 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "Rotation Speed" to value 60
Fri, 17 Jan 2020 09:32:59 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "On" to value true
[1/17/2020, 9:32:59 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:32:59 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:32:59 AM] [Roberta] ACT setSpeed | roborock.vacuum.s5 | Speed got 60% over HomeKit > CLEANUP.
[1/17/2020, 9:32:59 AM] [Roberta] ACT setSpeed | roborock.vacuum.s5 | FanSpeed set to 60 over miIO for "Balanced".
[1/17/2020, 9:32:59 AM] [Roberta] ACT setCleaning | roborock.vacuum.s5 | Start cleaning, not charging.
2020-01-17T09:32:59.784Z miio:packet -> <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
2020-01-17T09:32:59.800Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5e 21 7f 4b ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
2020-01-17T09:32:59.801Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5e 21 7f 4b ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
2020-01-17T09:32:59.801Z thing:miio:96818260 <- Handshake reply: <Buffer ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
```

4. Fourth final and sucessful try:
```
Fri, 17 Jan 2020 09:33:22 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "Lock Target State" to value 1
Fri, 17 Jan 2020 09:33:22 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "Rotation Speed" to value 60
Fri, 17 Jan 2020 09:33:22 GMT Accessory [raspberrypi-HomeBridge] Setting Characteristic "On" to value true
[1/17/2020, 9:33:22 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:33:22 AM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[1/17/2020, 9:33:22 AM] [Roberta] ACT setSpeed | roborock.vacuum.s5 | Speed got 60% over HomeKit > CLEANUP.
[1/17/2020, 9:33:22 AM] [Roberta] ACT setSpeed | roborock.vacuum.s5 | FanSpeed set to 60 over miIO for "Balanced".
[1/17/2020, 9:33:22 AM] [Roberta] ACT setCleaning | roborock.vacuum.s5 | Start cleaning, not charging.
2020-01-17T09:33:22.249Z thing:miio:96818260 -> (5) {"method":"set_custom_mode","params":[60],"id":1018}
2020-01-17T09:33:22.251Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 05 c5 54 54 5e 21 7f 61 ed 1c 1c 67 e9 c2 bc 16 a5 65 c3 87 73 e7 21 a1>
2020-01-17T09:33:22.252Z thing:miio:96818260 -> (5) {"method":"app_start","params":[],"id":1019}
2020-01-17T09:33:22.253Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 05 c5 54 54 5e 21 7f 61 42 ce e1 bc df 55 45 8f b6 63 eb 8b 38 a6 e4 a3>
2020-01-17T09:33:22.263Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 05 c5 54 54 5e 21 7f 62 b0 87 f4 58 ca d9 19 9f 12 68 95 df e6 2f e4 0c>
2020-01-17T09:33:22.263Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 05 c5 54 54 5e 21 7f 62 b0 87 f4 58 ca d9 19 9f 12 68 95 df e6 2f e4 0c>
2020-01-17T09:33:22.265Z thing:miio:96818260 <- Message: `{"result":["ok"],"id":1018}`
2020-01-17T09:33:22.296Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 05 c5 54 54 5e 21 7f 62 25 8a 4d 06 8b 75 b6 af fc a1 52 01 17 69 15 3a>
2020-01-17T09:33:22.296Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 05 c5 54 54 5e 21 7f 62 25 8a 4d 06 8b 75 b6 af fc a1 52 01 17 69 15 3a>
2020-01-17T09:33:22.298Z thing:miio:96818260 <- Message: `{"result":["ok"],"id":1019}`
```

We can see the plugin behaves as expected, setting the Characteristics to the right values. But the `miio` library is not properly sending the data to the robot. The logs show different outgoing messages in the failed scenarios vs. the successful one.
Good thing is that I didn't restart my `homebridge`. It simply got to solve the issue internally after a couple of retries. I wouldn't like simply adding retries at the plugin level, but fix it in the underlying communication library `miio`. I'll try to find some time to get to it. The backlog is growing and I'd appreciate some help.
I've recently changed jobs and I'm a bit overwhelmed with it. That is why I've been dormant with this project (sorry). I want to get it right.

**Comment by zlldnv** [comment]
@nicoh88 Thank you!
